### ISSUE TITLE
iOS Build Failing

### ISSUE THREAD

**Issue by aguilaair** [heremaps/here-sdk-examples#125]
```
[!] Unable to install vendored xcframework `heresdk` for Pod `here_sdk`, because it contains both static and dynamic frameworks.

    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:1182:in `block (2 levels) in validate_xcframeworks'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:1161:in `each'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:1161:in `block in validate_xcframeworks'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:1160:in `each_value'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:1160:in `validate_xcframeworks'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:67:in `block in install!'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:40:in `install!'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:115:in `block in install_pod_targets'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:112:in `map'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:112:in `install_pod_targets'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:149:in `message'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:314:in `block in create_and_save_projects'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:309:in `create_and_save_projects'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:301:in `generate_pods_project'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:180:in `integrate'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:167:in `install!'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `load'
    /usr/local/lib/ruby/gems/2.7.0/bin/pod:25:in `<main>'

Error: Process completed with exit code 1.
```

We are unsure of how to start debugging this issue running the latest here_sdk 4.10.4.0

**Comment by aguilaair** [comment]
Reproduced with the `hello_map_app` in addition to our app.

Full build logs: [build-log.txt](https://github.com/heremaps/here-sdk-examples/files/8239399/2.txt)

**Comment by datasun** [comment]
Please follow the quick start guide how to integrate the HERE SDK framework. It's (not yet) distributed via CocoaPods, so the framework has to be copied manually as explained in the guide. If this does not fix your issue, please leave a reply with more details on the steps you did. Thanks!

**Comment by aguilaair** [comment]
Hello @datasun 

Could you indicate the place in the quick start guide where it shows you how to handle this?

https://developer.here.com/documentation/flutter-sdk-explore/4.10.4.0/dev_guide/topics/quick-start.html#create-a-new-flutter-project-and-show-a-here-map

I followed this example and found myself in the same issue. 

I am not trying to install the here_sdk via cocoapods, it is in the plugins folder under the app, as indicated in the guide.

**Comment by datasun** [comment]
Ok, then please provide more details: Which version of the HERE SDK do you use? And: Can you print what "flutter doctor -v" prints to you? Thanks.

**Comment by aguilaair** [comment]
Hey @datasun,

I've tried with 2.10 and 2.8.1 flutter versions, both failing.

Flutter doctor is correct (all ticks), I will send the exact output tomorrow as I don't have it on hand.

The sdk version is on my first post, and the build logs for the example app as-is with only the plugin being added to it can be seen in my first comment, with android building successfully and iOS failing.

**Comment by aguilaair** [comment]
```
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.4 20G417 darwin-x64, locale en)
    • Flutter version 2.8.1 at /Users/runner/hostedtoolcache/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (3 months ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/runner/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/runner/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/runner/Library/Android/sdk
    • Java binary at: /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.322-6/x64/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
    • Xcode at /Applications/Xcode_13.0.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 99.0.4844.51

```

As you can see I am running XCode 13.0 and Flutter 2.8.1 as stated in the guide. Please note this machine is used for iOS development so Android is no set up completely. (This is GH actions)

I've also tested it in a Macbook, I will send the doctor's output when I get a chance.

**Comment by aguilaair** [comment]
![image](https://user-images.githubusercontent.com/29983481/158409501-82bfc3c5-210c-4583-9dd7-39c21e4230ae.png)

**Comment by datasun** [comment]
Thanks, @aguilaair. Your doctor output looks correct. We know from our tests and CI that `flutter build ios` should work with your configuration, so it will be a bit hard to help you here on GitHub.

Please open up a ticket through our [customer support](https://developer.here.com/help), so we can investigate this issue properly. Or raise this with your direct HERE contact, if you have. Thanks!

**Comment by datasun** [comment]
@aguilaair Thanks! We will reply as soon as possible. For now the rough guess is that there may be some fragile setup issue with CocoaPods that sometimes can lead to such strange errors. But we will reply with a proper investigation. Thanks again, for raising.
