### ISSUE TITLE
Manual SDK initialization errors

### ISSUE THREAD

**Issue by incloudss** [heremaps/here-sdk-examples#144]
Hi,

I am trying to initialize manually Here Navigation SDK. The initialization seems to work, the map loads, i can run turn by turn navigation and so on, but i am getting two errors in console and i am afraid that the problem related to them will get me sooner than later.

First one: 
```
E/ActivityThread( 5474): android.app.IntentReceiverLeaked: Service com.here.services.internal.LocationService has leaked IntentReceiver com.here.odnp.cell.PlatformCellManager$1@d189c1d that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread( 5474): 	at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1538)
E/ActivityThread( 5474): 	at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1277)
E/ActivityThread( 5474): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1555)
E/ActivityThread( 5474): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1528)
E/ActivityThread( 5474): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1516)
E/ActivityThread( 5474): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:636)
E/ActivityThread( 5474): 	at com.here.odnp.cell.PlatformCellManager.registerScreenEvents(Unknown Source:19)
E/ActivityThread( 5474): 	at com.here.odnp.cell.PlatformCellManager.access$400(Unknown Source:0)
E/ActivityThread( 5474): 	at com.here.odnp.cell.PlatformCellManager$2.run(Unknown Source:46)
E/ActivityThread( 5474): 	at android.os.Handler.handleCallback(Handler.java:873)
E/ActivityThread( 5474): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/ActivityThread( 5474): 	at android.os.Looper.loop(Looper.java:214)
E/ActivityThread( 5474): 	at android.os.HandlerThread.run(HandlerThread.java:65)
I/OLP     ( 5474): [INFO ] OLP - PrewarmConnection: completed for url='https://direct.data.api.platform.here.com/direct/v1/direct', status='200 OK'
```

Second one:
```
/inclouds.motog( 5474): Rejecting re-init on previously-failed class java.lang.Class<Kp2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:176)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:459)
I/inclouds.motog( 5474):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:251)
I/inclouds.motog( 5474):   at java.lang.String android.webkit.WebSettings.getDefaultUserAgent(android.content.Context) (WebSettings.java:1266)
inclouds.motog( 5474): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.PacProcessor" on path: DexPathList[[zip file "/data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/lib/arm64, /data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/base.apk!/lib/arm64-v8a, /system/lib64]]
I/inclouds.motog( 5474):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:176)
inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:459)
I/inclouds.motog( 5474):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:251)
I/inclouds.motog( 5474):   at java.lang.String android.webkit.WebSettings.getDefaultUserAgent(android.content.Context) (WebSettings.java:1266)
I/inclouds.motog( 5474):
I/inclouds.motog( 5474): Rejecting re-init on previously-failed class java.lang.Class<Kp2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:176)
inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:459)
I/inclouds.motog( 5474):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:251)
I/inclouds.motog( 5474):   at java.lang.String android.webkit.WebSettings.getDefaultUserAgent(android.content.Context) (WebSettings.java:1266)
I/inclouds.motog( 5474): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.PacProcessor" on path: DexPathList[[zip file "/data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/lib/arm64, /data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/base.apk!/lib/arm64-v8a, /system/lib64]]
I/inclouds.motog( 5474):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
inclouds.motog( 5474):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:176)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:459)
I/inclouds.motog( 5474):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:251)
I/inclouds.motog( 5474):   at java.lang.String android.webkit.WebSettings.getDefaultUserAgent(android.content.Context) (WebSettings.java:1266)
I/inclouds.motog( 5474):
I/inclouds.motog( 5474): Rejecting re-init on previously-failed class java.lang.Class<Kp2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:176)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:459)
I/inclouds.motog( 5474):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:251)
I/inclouds.motog( 5474):   at java.lang.String android.webkit.WebSettings.getDefaultUserAgent(android.content.Context) (WebSettings.java:1266)
I/inclouds.motog( 5474): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.PacProcessor" on path: DexPathList[[zip file "/data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/lib/arm64, /data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/base.apk!/lib/arm64-v8a, /system/lib64]]
I/inclouds.motog( 5474):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:176)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:459)
I/inclouds.motog( 5474):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:251)
/inclouds.motog( 5474):   at java.lang.String android.webkit.WebSettings.getDefaultUserAgent(android.content.Context) (WebSettings.java:1266)
I/inclouds.motog( 5474):
I/inclouds.motog( 5474): Rejecting re-init on previously-failed class java.lang.Class<Kp2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/PacProcessor;
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:176)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:459)
I/inclouds.motog( 5474):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:251)
/inclouds.motog( 5474):   at java.lang.String android.webkit.WebSettings.getDefaultUserAgent(android.content.Context) (WebSettings.java:1266)
I/inclouds.motog( 5474): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.PacProcessor" on path: DexPathList[[zip file "/data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/lib/arm64, /data/app/com.android.chrome-d_VNqhP_s5o2QfDqjes8CA==/base.apk!/lib/arm64-v8a, /system/lib64]]
I/inclouds.motog( 5474):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/inclouds.motog( 5474):   at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:176)
I/inclouds.motog( 5474):   at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:459)
I/inclouds.motog( 5474):   at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:251)
I/inclouds.motog( 5474):   at java.lang.String android.webkit.WebSettings.getDefaultUserAgent(android.content.Context) (WebSettings.java:1266)
```

My code:
```
class MainActivity : FlutterFragmentActivity() {
    private val HERE_INIT_CHANNEL = "com.inclouds.motogo/here"

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        MethodChannel(flutterEngine.dartExecutor, HERE_INIT_CHANNEL).setMethodCallHandler(
                MethodChannel.MethodCallHandler { call, result ->
                    if (call.method == "manualInit") {
                        try {
                            initializeHereSdk(KEY, SECRET)
                            result.success(null)
                        } catch (e: InstantiationErrorException) {
                            result.error("NoCode", e.message, e.toString())
                        }
                    } else
                        result.notImplemented()
                }
        );
    }

    private fun initializeHereSdk(key: String, secret: String){
        System.loadLibrary("heresdk")
        SDKNativeEngine.getSharedInstance()?.dispose()

        InitProvider.initialize(applicationContext)

        val sdkOptions = SDKOptions(key, secret)
        val sdkNativeEngine = SDKNativeEngine(sdkOptions)
        SDKNativeEngine.setSharedInstance(sdkNativeEngine)
    }
}

```

Do you have any idea what i may be doing wrong?

**Comment by datasun** [comment]
Thanks for raising. Can you please contact our technical support team? These log messages look related to positioning. Are you using the `LocationEngine`? Either way, please contact us via help page, so we can create a ticket and you can more easily track the process. Thanks!
