### ISSUE TITLE
Crash due to library not being able to load on OnePlus Nord 3 5G

### ISSUE THREAD

**Issue by danielqvisthiq** [heremaps/here-sdk-examples#292]
Found a crash happening for a user with OnePlus Nord 3 5G due to the library not being able to load, works as intended for other endusers.

Currently using the navigate edition with version 4.16.2

```
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libheresdk.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
       at java.lang.System.loadLibrary(System.java:1661)
       at com.here.sdk.core.SDKLibraryLoader.loadLibraries(SDKLibraryLoader.java:75)
       at com.here.sdk.core.SDKLibraryLoader.<init>(SDKLibraryLoader.java:41)
       at com.here.sdk.core.engine.SDKNativeEngine.<clinit>(SDKNativeEngine.java:38)
```

**Comment by HERE-SDK-Support-Team** [comment]
Thanks for reporting! It looks like this may require more input. Can you file a ticket via our help desk: https://developer.here.com/help ? Make sure to provide enough details as listed in this [checklist](https://www.here.com/docs/bundle/sdk-for-android-navigate-developer-guide/page/topics/key-concepts.html#contact-us). This repository and its issue tracking are meant for issues with the hosted example apps and this issue does not look like it is related to any example app hosted in this repository. Via help desk you can share your account details and example code, so it will be easier and faster for us to help you. Thanks!
