### ISSUE TITLE
Android, Navigate Edition: MapView is not life cycle proof

### ISSUE THREAD

**Issue by SergeHelfrichPI** [heremaps/here-sdk-examples#298]
Android, Navigate Edition: MapView is not life cycle proof

We're using the HERE SDK Navigate Edition, version 4.17. On orientation change onDestroy is called on the MapView. After recreation the first method call on the MapView causes the application to crash: "java.lang.IllegalStateException: Please call MapView.onCreate() before calling any other MapView methods."

Steps to reproduce in the 'Navigation' example:

- Remove from MainActivity.java:
```
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LOCKED);
```

- Remove 'orientation' from the config changes in the manifest:
```
<activity android:name=".MainActivity"
                  android:exported="true"
                  android:configChanges="orientation|screenSize|screenLayout|keyboardHidden">
```

Build, run and rotate the device. Crash on:
```
mapView.getMapScene() ...
```

Stack trace:

```
FATAL EXCEPTION: main
Process: com.here.navigation, PID: 22095
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.here.navigation/com.here.navigation.MainActivity}: java.lang.IllegalStateException: Please call MapView.onCreate() before calling any other MapView methods.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2791)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2869)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4712)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6528)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Please call MapView.onCreate() before calling any other MapView methods.
	at com.here.sdk.mapview.MapView.checkMapViewInternalInitialized(MapView.java:1383)
	at com.here.sdk.mapview.MapView.getMapScene(MapView.java:1259)
	at com.here.navigation.MainActivity.loadMapScene(MainActivity.java:162)
	at com.here.navigation.MainActivity.access$000(MainActivity.java:54)
	at com.here.navigation.MainActivity$1.permissionsGranted(MainActivity.java:145)
	at com.here.navigation.PermissionsRequestor.request(PermissionsRequestor.java:56)
	at com.here.navigation.MainActivity.handleAndroidPermissions(MainActivity.java:141)
	at com.here.navigation.MainActivity.onCreate(MainActivity.java:88)
	at android.app.Activity.performCreate(Activity.java:7026)
	at android.app.Activity.performCreate(Activity.java:7017)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2744)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2869) 
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4712) 
	at android.app.ActivityThread.-wrap18(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1608) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loop(Looper.java:164) 
	at android.app.ActivityThread.main(ActivityThread.java:6528) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by HERE-SDK-Support-Team** [comment]
Hi @SergeHelfrichPI, sorry for the late reply and thank you for your detailed question. With the steps listed, this is expected, in such a case you need to recreate the map view. Basically, this is what the error message is indicating. 

```java
@Override
protected void onPause() {
    mapView.onPause();
    super.onPause();
}

@Override
protected void onResume() {
    mapView.onResume();
    super.onResume();
}

@Override
protected void onDestroy() {
    mapView.onDestroy();
    disposeHERESDK();
    super.onDestroy();
}

@Override
protected void onSaveInstanceState(@NonNull Bundle outState) {
    mapView.onSaveInstanceState(outState);
    super.onSaveInstanceState(outState);
}
```

When you call `mapView.onSaveInstanceState(outState)` then all map items that are added to the map, like markers, polylines and so on, will be kept based on the bundled state - even if the screen orientation changes. However, if instead you want to create a _new_ map view instance for each orientation change, then make sure to reinitialize the HERE SDK and call `mapView.onSaveInstanceState(null)` - a new HERE SDK instance or likewise a new `MapView` instance cannot be used together with a bundled state that was created based on previous instances.

If this answer is not sufficient, please leave a reply. Thank you!

**Comment by PicsArt01** [comment]
"This blog post couldn't have come at a better time! I've been on the lookout for a good photo editing app, and **[PicsArt Mod APK](https://picsart.apkflames.com/)** seems like the perfect fit. I can't wait to give it a try and see what all the hype is about."

**Comment by PicsArt01** [comment]
What an insightful post on creativity! Your thoughts really resonated with me. I wanted to contribute to the conversation by mentioning an article I read on PicsArt's website about the <a href="https://picsart.apkflames.com/"> Picsart Mod APK </a>. It explores how this tool is revolutionizing the way artists express themselves digitally, which I think adds an interesting dimension to your discussion.
